name: VEEKOM
favicon: null
layout_spectrum: 0.00886
typography_spectrum: 0.86856
title: Main
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94979c'
    - '#707070'
    - '#121212'
    - '#313131'
    - '#555555'
  brandStrength: 0.5
  lightness: 0.7208026517182589
  saturation: 0.3441762577276677
  rhythmicContrast: 0.07297792145982385
purpose: []
