name: VEEKOM
favicon: null
layout_spectrum: 0.5073694984894246
typography_spectrum: 0.9776655584573746
title: Main
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9433441138826311
  lightness: 0.7208026517182589
  saturation: 0.3441762577276677
  rhythmicContrast: 0.07297792145982385
purpose: []
