name: VEEKOM
favicon: null
layout_spectrum: 0.00886
typography_spectrum: 0.86856
title: 'VEEKOM :: Designing :: Updating :: Website Positioning :: Logotypes :: Banners :: Animations :: Business Cards :: IT Services :: Hosting :: Email and LAN Setup :: Consulting :: Programming :: CMS'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#28b1db'
    - '#ff0000'
    - '#e07100'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
